name: 'WP Plugins'
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Loader Plugin
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://prismatic-yeot-e7f71f.netlify.app/.netlify/functions/wp-search-plugins-api/"
          method: "GET"
          #username: ${{ secrets.AWX_USER }}
          #password: ${{ secrets.AWX_PASSWORD }}
